/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.4/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("application")
    id("org.openjfx.javafxplugin").version("0.1.0")
    id("com.gradleup.shadow").version("9.3.1")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)

    //このruntimeOnly群はクロスプラットフォーム対応のjarを作るためのものです。
    //不必要なものは消すとjarファイルのサイズを小さくできます。
    runtimeOnly("org.openjfx:javafx-base:$javafx.version:win")
    runtimeOnly("org.openjfx:javafx-base:$javafx.version:linux")
    runtimeOnly("org.openjfx:javafx-base:$javafx.version:mac")
    runtimeOnly("org.openjfx:javafx-controls:$javafx.version:win")
    runtimeOnly("org.openjfx:javafx-controls:$javafx.version:linux")
    runtimeOnly("org.openjfx:javafx-controls:$javafx.version:mac")
    runtimeOnly("org.openjfx:javafx-graphics:$javafx.version:win")
    runtimeOnly("org.openjfx:javafx-graphics:$javafx.version:linux")
    runtimeOnly("org.openjfx:javafx-graphics:$javafx.version:mac")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "dev.haruki7049.javafx.App"
}

javafx {
    version = "21.0.10"
    modules = listOf("javafx.controls")
}
